spring:
  application:
    name: mini

  profiles:
    active: new

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-authentication-method: client_secret_post
            redirect-uri: https://api.miniteam2.store/api/auth/kakao/callback
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - account_email
          google:
            redirect-uri: https://api.miniteam2.store/api/auth/google/callback
            authorization-grant-type: authorization_code
            client-name: google
            scope:
              - email
              - profile

server:
  ssl:
    key-store: /app/cert.p12
    key-store-password: kwonjongwon
    keyStoreType: PKCS12