spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tourapp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1217

  sql:
    init:
      data-locations: classpath*:db/data.sql
      mode: always
      platform:

