spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tourapp
    username: root
    password: 1217
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      data-locations: classpath*:data/data.sql
      mode: always
      platform: